// Heidelberg Catechism (1563) — public domain
export default async function seedHeidel(sql: any): Promise<void> {
  const qs = [
    // Lord's Day 1
    { n:1, ld:"Lord's Day 1", lname:"Our Only Comfort",
      q:"What is your only comfort in life and in death?",
      a:"That I am not my own, but belong — body and soul, in life and in death — to my faithful Savior, Jesus Christ. He has fully paid for all my sins with his precious blood, and has set me free from the tyranny of the devil. He also watches over me in such a way that not a hair can fall from my head without the will of my Father in heaven; in fact, all things must work together for my salvation. Because I belong to him, Christ, by his Holy Spirit, assures me of eternal life and makes me wholeheartedly willing and ready from now on to live for him.",
      p:[{reference:"Romans 8:38-39",text:"Neither death, nor life...shall be able to separate us from the love of God, which is in Christ Jesus our Lord."},{reference:"1 Corinthians 6:19-20",text:"Ye are not your own. For ye are bought with a price."}] },
    { n:2, ld:"Lord's Day 1", lname:"Our Only Comfort",
      q:"What must you know to live and die in the joy of this comfort?",
      a:"Three things: first, how great my sin and misery are; second, how I am set free from all my sins and their wretched consequences; third, how I am to thank God for such deliverance.",
      p:[{reference:"Matthew 11:28-30",text:"Come unto me, all ye that labour and are heavy laden, and I will give you rest."},{reference:"Luke 24:47",text:"That repentance and remission of sins should be preached in his name among all nations."}] },
    // Lord's Day 2
    { n:3, ld:"Lord's Day 2", lname:"Our Misery",
      q:"Where do you learn of your sin and its wretched consequences?",
      a:"From the law of God.",
      p:[{reference:"Romans 3:20",text:"By the law is the knowledge of sin."}] },
    { n:4, ld:"Lord's Day 2", lname:"Our Misery",
      q:"What does God's law require of us?",
      a:"Christ teaches us this in a summary in Matthew 22: You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment. And a second is like it: You shall love your neighbor as yourself. On these two commandments depend all the Law and the Prophets.",
      p:[{reference:"Matthew 22:37-40",text:"Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment."}] },
    { n:5, ld:"Lord's Day 2", lname:"Our Misery",
      q:"Can you live up to all this perfectly?",
      a:"No. I have a natural tendency to hate God and my neighbor.",
      p:[{reference:"Romans 3:10-12",text:"There is none righteous, no, not one: There is none that understandeth, there is none that seeketh after God."},{reference:"Romans 8:7",text:"The carnal mind is enmity against God."}] },
    // Lord's Day 3
    { n:6, ld:"Lord's Day 3", lname:"Our Corrupt Nature",
      q:"Did God create people so wicked and perverse?",
      a:"No. God created them good and in his own image, that is, in true righteousness and holiness, so that they might truly know God their creator, love him with all their heart, and live with God in eternal happiness, to praise and glorify him.",
      p:[{reference:"Genesis 1:31",text:"And God saw every thing that he had made, and, behold, it was very good."},{reference:"Ephesians 4:24",text:"Put on the new man, which after God is created in righteousness and true holiness."}] },
    { n:7, ld:"Lord's Day 3", lname:"Our Corrupt Nature",
      q:"Then where does this corrupt human nature come from?",
      a:"From the fall and disobedience of our first parents, Adam and Eve, in Paradise. This fall has so poisoned our nature that we are born sinners — corrupt from conception on.",
      p:[{reference:"Genesis 3:1-6",text:"And when the woman saw that the tree was good for food...she took of the fruit thereof, and did eat."},{reference:"Romans 5:12",text:"By one man sin entered into the world, and death by sin."}] },
    { n:8, ld:"Lord's Day 3", lname:"Our Corrupt Nature",
      q:"But are we so corrupt that we are totally unable to do any good and inclined toward all evil?",
      a:"Yes, unless we are born again by the Spirit of God.",
      p:[{reference:"John 3:5",text:"Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God."},{reference:"Genesis 6:5",text:"And God saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually."}] },
    // Lord's Day 4
    { n:9, ld:"Lord's Day 4", lname:"God's Wrath Against Sin",
      q:"But doesn't God do us an injustice by requiring in his law what we are unable to do?",
      a:"No, God created human beings with the ability to keep the law. They, however, provoked by the devil, in deliberate disobedience, robbed themselves and all their descendants of these gifts.",
      p:[{reference:"Romans 5:12",text:"By one man sin entered into the world, and death by sin; and so death passed upon all men, for that all have sinned."}] },
    { n:10, ld:"Lord's Day 4", lname:"God's Wrath Against Sin",
      q:"Will God permit such disobedience and rebellion to go unpunished?",
      a:"Certainly not. God is terribly angry with the sin we are born with as well as the sins we personally commit. As a just judge, God will punish them both now and in eternity, having declared: Cursed is everyone who does not observe and obey all things written in the book of the law.",
      p:[{reference:"Galatians 3:10",text:"Cursed is every one that continueth not in all things which are written in the book of the law to do them."},{reference:"Romans 1:18",text:"The wrath of God is revealed from heaven against all ungodliness and unrighteousness of men."}] },
    { n:11, ld:"Lord's Day 4", lname:"God's Wrath Against Sin",
      q:"But isn't God also merciful?",
      a:"God is certainly merciful, but he is also just. His justice demands that sin, committed against his supreme majesty, be punished with the supreme penalty — eternal punishment of body and soul.",
      p:[{reference:"Exodus 34:6-7",text:"The LORD, The LORD God, merciful and gracious...and that will by no means clear the guilty."},{reference:"Romans 2:5",text:"After thy hardness and impenitent heart treasurest up unto thyself wrath against the day of wrath."}] },
    // Lord's Day 5
    { n:12, ld:"Lord's Day 5", lname:"Our Deliverance",
      q:"According to God's righteous judgment we deserve punishment both in this world and forever after: how then can we escape this punishment and return to God's favor?",
      a:"God requires that his justice be satisfied. Therefore the claims of his justice must be paid in full, either by ourselves or another.",
      p:[{reference:"Romans 8:3-4",text:"God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh."},{reference:"Isaiah 53:11",text:"By his knowledge shall my righteous servant justify many; for he shall bear their iniquities."}] },
    { n:13, ld:"Lord's Day 5", lname:"Our Deliverance",
      q:"Can we pay this debt ourselves?",
      a:"Certainly not. Actually, we increase our debt every day.",
      p:[{reference:"Matthew 6:12",text:"Forgive us our debts, as we forgive our debtors."},{reference:"Romans 2:5",text:"Thou treasurest up unto thyself wrath against the day of wrath."}] },
    { n:14, ld:"Lord's Day 5", lname:"Our Deliverance",
      q:"Can another creature — any at all — pay this debt for us?",
      a:"No. To begin with, God will not punish another creature for what a human is guilty of. Besides, no mere creature can bear the weight of God's eternal anger against sin and release others from it.",
      p:[{reference:"Hebrews 2:14-16",text:"He also himself likewise took part of the same; that through death he might destroy him that had the power of death."}] },
    { n:15, ld:"Lord's Day 5", lname:"Our Deliverance",
      q:"What kind of mediator and deliverer should we look for then?",
      a:"One who is truly human and truly righteous, yet more powerful than all creatures, that is, one who is also truly God.",
      p:[{reference:"1 Timothy 2:5",text:"For there is one God, and one mediator between God and men, the man Christ Jesus."},{reference:"Jeremiah 23:6",text:"And this is his name whereby he shall be called, THE LORD OUR RIGHTEOUSNESS."}] },
    // Lord's Day 6
    { n:16, ld:"Lord's Day 6", lname:"The True Mediator",
      q:"Why must the mediator be truly human and truly righteous?",
      a:"God's justice demands that human nature, which has sinned, must pay for its sin; but a sinner could not pay for others.",
      p:[{reference:"Romans 5:12-15",text:"By one man sin entered into the world...the gift by grace...hath abounded unto many."},{reference:"Hebrews 2:17",text:"In all things it behoved him to be made like unto his brethren."}] },
    { n:17, ld:"Lord's Day 6", lname:"The True Mediator",
      q:"Why must the mediator also be truly God?",
      a:"So that, by the power of his divinity, he might bear the weight of God's anger in his humanity and earn for us and restore to us righteousness and life.",
      p:[{reference:"Isaiah 53:8",text:"For the transgression of my people was he stricken."},{reference:"Acts 2:24",text:"Whom God hath raised up, having loosed the pains of death."}] },
    { n:18, ld:"Lord's Day 6", lname:"The True Mediator",
      q:"Then who is this mediator — true God and at the same time truly human and truly righteous?",
      a:"Our Lord Jesus Christ, who was given to us to set us completely free and to make us right with God.",
      p:[{reference:"Matthew 1:23",text:"Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us."},{reference:"Luke 2:11",text:"Unto you is born this day in the city of David a Saviour, which is Christ the Lord."}] },
    { n:19, ld:"Lord's Day 6", lname:"The True Mediator",
      q:"Where does the gospel tell us this?",
      a:"The holy gospel tells us this already in the Garden of Eden, when God said to the serpent: I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel. God also spoke of him through the holy prophets and proclaimed him in the sacrifices and other ceremonies of the law; and finally God fulfilled the law through his only Son.",
      p:[{reference:"Genesis 3:15",text:"I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head."},{reference:"Galatians 4:4-5",text:"When the fulness of the time was come, God sent forth his Son, made of a woman, made under the law, to redeem them that were under the law."}] },
    // Lord's Day 7
    { n:20, ld:"Lord's Day 7", lname:"True Faith",
      q:"Are all people then saved through Christ just as they were lost through Adam?",
      a:"No. Only those are saved who through true faith are grafted into Christ and accept all his blessings.",
      p:[{reference:"Matthew 7:14",text:"Strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it."},{reference:"John 3:16",text:"Whosoever believeth in him should not perish, but have everlasting life."}] },
    { n:21, ld:"Lord's Day 7", lname:"True Faith",
      q:"What is true faith?",
      a:"True faith is not only a reliable knowledge by which I hold as true all that God has revealed to us in Scripture, but also a wholehearted trust, which the Holy Spirit creates in me by the gospel, that God has freely granted, not only to others but to me also, forgiveness of sins, eternal righteousness, and salvation. These are gifts of sheer grace, granted solely by Christ's merit.",
      p:[{reference:"Hebrews 11:1",text:"Now faith is the substance of things hoped for, the evidence of things not seen."},{reference:"James 2:19",text:"Thou believest that there is one God; thou doest well: the devils also believe, and tremble."}] },
    { n:22, ld:"Lord's Day 7", lname:"True Faith",
      q:"What then must a Christian believe?",
      a:"Everything God promises us in the gospel. That gospel is summarized for us in the articles of our Christian faith — a creed beyond doubt, and confessed throughout the world.",
      p:[{reference:"Matthew 28:19",text:"Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost."},{reference:"John 20:31",text:"These are written, that ye might believe that Jesus is the Christ, the Son of God."}] },
    { n:23, ld:"Lord's Day 7", lname:"True Faith",
      q:"What are these articles?",
      a:"I believe in God, the Father almighty, creator of heaven and earth. I believe in Jesus Christ, his only-begotten Son, our Lord, who was conceived by the Holy Spirit and born of the virgin Mary. He suffered under Pontius Pilate, was crucified, died, and was buried; he descended into hell. The third day he rose again from the dead. He ascended to heaven and is seated at the right hand of God the Father almighty. From there he will come to judge the living and the dead. I believe in the Holy Spirit, the holy catholic church, the communion of saints, the forgiveness of sins, the resurrection of the body, and the life everlasting. Amen.",
      p:[{reference:"Romans 10:9",text:"If thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved."}] },
    // Lord's Day 8
    { n:24, ld:"Lord's Day 8", lname:"The Trinity",
      q:"How are these articles divided?",
      a:"Into three parts: God the Father and our creation; God the Son and our deliverance; God the Holy Spirit and our sanctification.",
      p:[{reference:"Matthew 28:19",text:"Baptizing them in the name of the Father, and of the Son, and of the Holy Ghost."}] },
    { n:25, ld:"Lord's Day 8", lname:"The Trinity",
      q:"Since there is only one God, why do you speak of three: Father, Son, and Holy Spirit?",
      a:"Because that is how God has revealed himself in his Word: these three distinct persons are one, true, eternal God.",
      p:[{reference:"Deuteronomy 6:4",text:"Hear, O Israel: The LORD our God is one LORD."},{reference:"2 Corinthians 13:14",text:"The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all."}] },
    // Lord's Day 9
    { n:26, ld:"Lord's Day 9", lname:"God the Father",
      q:"What do you believe when you say: I believe in God, the Father almighty, creator of heaven and earth?",
      a:"That the eternal Father of our Lord Jesus Christ, who out of nothing created heaven and earth and everything in them, who still upholds and rules them by his eternal counsel and providence, is my God and Father because of Christ his Son. I trust him so much that I do not doubt he will provide whatever I need for body and soul, and he will turn to my good whatever adversity he sends me in this sad world. He is able to do this because he is almighty God; he desires to do this because he is a faithful Father.",
      p:[{reference:"Genesis 1:1",text:"In the beginning God created the heaven and the earth."},{reference:"Matthew 6:26",text:"Behold the fowls of the air: for they sow not, neither do they reap...yet your heavenly Father feedeth them."}] },
    // Lord's Day 10
    { n:27, ld:"Lord's Day 10", lname:"Providence",
      q:"What do you understand by the providence of God?",
      a:"Providence is the almighty and ever present power of God by which God upholds, as with his hand, heaven and earth and all creatures, and so rules them that leaf and blade, rain and drought, fruitful and lean years, food and drink, health and sickness, prosperity and poverty — all things, in fact, come to us not by chance but from his fatherly hand.",
      p:[{reference:"Hebrews 1:3",text:"Upholding all things by the word of his power."},{reference:"Matthew 10:29",text:"Are not two sparrows sold for a farthing? and one of them shall not fall on the ground without your Father."}] },
    { n:28, ld:"Lord's Day 10", lname:"Providence",
      q:"How does the knowledge of God's creation and providence help us?",
      a:"We can be patient when things go against us, thankful when things go well, and for the future we can have good confidence in our faithful God and Father that nothing will separate us from his love. All creatures are so completely in his hand that without his will they can neither move nor be moved.",
      p:[{reference:"Romans 5:3-4",text:"We glory in tribulations also: knowing that tribulation worketh patience."},{reference:"Romans 8:38-39",text:"Neither death, nor life...shall be able to separate us from the love of God."}] },
    // Lord's Day 11
    { n:29, ld:"Lord's Day 11", lname:"Jesus Christ Our Savior",
      q:"Why is the Son of God called Jesus, meaning Savior?",
      a:"Because he saves us from our sins. Salvation cannot be found in anyone else; it is futile to look for any salvation elsewhere.",
      p:[{reference:"Matthew 1:21",text:"She shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins."},{reference:"Acts 4:12",text:"Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved."}] },
    { n:30, ld:"Lord's Day 11", lname:"Jesus Christ Our Savior",
      q:"Do those who look for their salvation and well-being in saints, in themselves, or elsewhere, also believe in the only Savior Jesus?",
      a:"They do not. Although they boast of him in words, they deny the only Savior and Deliverer, Jesus. Either Jesus is not a perfect Savior, or those who in true faith accept this Savior have in him all they need for their salvation.",
      p:[{reference:"1 Corinthians 1:30",text:"But of him are ye in Christ Jesus, who of God is made unto us wisdom, and righteousness, and sanctification, and redemption."},{reference:"Colossians 1:19-20",text:"For it pleased the Father that in him should all fulness dwell."}] },
    // Lord's Day 12
    { n:31, ld:"Lord's Day 12", lname:"Christ Our Prophet, Priest, and King",
      q:"Why is he called Christ, meaning Anointed?",
      a:"Because he has been ordained by God the Father and has been anointed with the Holy Spirit to be our chief prophet and teacher who perfectly reveals to us the secret counsel and will of God for our deliverance; our only high priest who has set us free by the one sacrifice of his body, and who continually pleads our cause with the Father; and our eternal king who governs us by his Word and Spirit, and who guards us and keeps us in the freedom he has won for us.",
      p:[{reference:"Luke 4:18",text:"The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor."},{reference:"Hebrews 7:17",text:"Thou art a priest for ever after the order of Melchisedec."}] },
    { n:32, ld:"Lord's Day 12", lname:"Christ Our Prophet, Priest, and King",
      q:"But why are you called a Christian?",
      a:"Because by faith I am a member of Christ and so I share in his anointing. I am anointed to confess his name, to present myself to him as a living sacrifice of thanks, to strive with a good conscience against sin and the devil in this life, and afterward to reign with Christ over all creation for all eternity.",
      p:[{reference:"1 John 2:27",text:"The anointing which ye have received of him abideth in you."},{reference:"1 Peter 2:9",text:"Ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people."}] },
    // Lord's Day 13
    { n:33, ld:"Lord's Day 13", lname:"Son of God, Our Lord",
      q:"Why is he called God's only Son when we also are God's children?",
      a:"Because Christ alone is the eternal, natural Son of God. We, however, are adopted children of God — adopted by grace through Christ.",
      p:[{reference:"John 1:1",text:"In the beginning was the Word, and the Word was with God, and the Word was God."},{reference:"Romans 8:15-17",text:"Ye have received the Spirit of adoption, whereby we cry, Abba, Father."}] },
    { n:34, ld:"Lord's Day 13", lname:"Son of God, Our Lord",
      q:"Why do you call him our Lord?",
      a:"Because — not with gold or silver, but with his precious blood — he has set us free from sin and from the tyranny of the devil, and has bought us, body and soul, to be his very own.",
      p:[{reference:"1 Peter 1:18-19",text:"Ye were not redeemed with corruptible things, as silver and gold...But with the precious blood of Christ."},{reference:"1 Corinthians 6:20",text:"For ye are bought with a price: therefore glorify God in your body."}] },
    // Lord's Day 14
    { n:35, ld:"Lord's Day 14", lname:"The Holy Conception",
      q:"What does it mean that he was conceived by the Holy Spirit and born of the virgin Mary?",
      a:"That the eternal Son of God, who is and remains true and eternal God, took to himself, through the working of the Holy Spirit, from the flesh and blood of the virgin Mary, a truly human nature so that he might become David's true descendant, like his brothers and sisters in every way except for sin.",
      p:[{reference:"Luke 1:35",text:"The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee."},{reference:"Galatians 4:4",text:"God sent forth his Son, made of a woman, made under the law."}] },
    { n:36, ld:"Lord's Day 14", lname:"The Holy Conception",
      q:"How does the holy conception and birth of Christ benefit you?",
      a:"He is our mediator, and with his innocence and perfect holiness he removes from God's sight my sin — mine since I was conceived.",
      p:[{reference:"Romans 8:3-4",text:"God sending his own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh."},{reference:"2 Corinthians 5:21",text:"He hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him."}] },
    // Lord's Day 15
    { n:37, ld:"Lord's Day 15", lname:"The Suffering of Christ",
      q:"What do you understand by the word suffered?",
      a:"That during his whole life on earth, but especially at the end, Christ sustained in body and soul the anger of God against the sin of the whole human race. This he did in order that, by his suffering as the only atoning sacrifice, he might set us free, body and soul, from eternal condemnation, and gain for us God's grace, righteousness, and eternal life.",
      p:[{reference:"Isaiah 53:12",text:"He hath poured out his soul unto death: and he was numbered with the transgressors."},{reference:"1 Peter 2:24",text:"Who his own self bare our sins in his own body on the tree."}] },
    { n:38, ld:"Lord's Day 15", lname:"The Suffering of Christ",
      q:"Why did he suffer under Pontius Pilate as judge?",
      a:"So that he, though innocent, might be condemned by a civil judge, and so free us from the severe judgment of God that was to fall on us.",
      p:[{reference:"Luke 23:14",text:"I, having examined him before you, have found no fault in this man."},{reference:"2 Corinthians 5:21",text:"He hath made him to be sin for us, who knew no sin."}] },
    { n:39, ld:"Lord's Day 15", lname:"The Suffering of Christ",
      q:"Is it significant that he was crucified and did not die some other way?",
      a:"Yes. This death convinces me that he shouldered the curse that lay on me, since death by crucifixion was accursed by God.",
      p:[{reference:"Galatians 3:13",text:"Christ hath redeemed us from the curse of the law, being made a curse for us: for it is written, Cursed is every one that hangeth on a tree."}] },
    // Lord's Day 16
    { n:40, ld:"Lord's Day 16", lname:"The Death and Burial of Christ",
      q:"Why did Christ have to go all the way to death?",
      a:"Because God's justice and truth demand it: only the death of God's Son could pay for our sin.",
      p:[{reference:"Romans 3:25-26",text:"Whom God hath set forth to be a propitiation through faith in his blood, to declare his righteousness."},{reference:"Genesis 2:17",text:"In the day that thou eatest thereof thou shalt surely die."}] },
    { n:41, ld:"Lord's Day 16", lname:"The Death and Burial of Christ",
      q:"Why was he buried?",
      a:"His burial testifies that he really died.",
      p:[{reference:"John 19:38-42",text:"He came therefore, and took the body of Jesus...There laid they Jesus."}] },
    { n:42, ld:"Lord's Day 16", lname:"The Death and Burial of Christ",
      q:"Since Christ has died for us, why do we still have to die?",
      a:"Our death does not pay the debt of our sins. Rather, it puts an end to our sinning and is our entrance into eternal life.",
      p:[{reference:"John 5:24",text:"He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life."}] },
    { n:43, ld:"Lord's Day 16", lname:"The Death and Burial of Christ",
      q:"What further benefit do we receive from Christ's sacrifice and death on the cross?",
      a:"Through Christ's death our old selves are crucified, put to death, and buried with him, so that the evil desires of the flesh may no longer rule us, but that instead we may dedicate ourselves as an offering of gratitude to him.",
      p:[{reference:"Romans 6:6",text:"Our old man is crucified with him, that the body of sin might be destroyed, that henceforth we should not serve sin."},{reference:"Colossians 2:12",text:"Buried with him in baptism, wherein also ye are risen with him through the faith of the operation of God."}] },
    { n:44, ld:"Lord's Day 16", lname:"The Death and Burial of Christ",
      q:"Why does the creed add: He descended into hell?",
      a:"To assure me during attacks of deepest dread and temptation that Christ my Lord, by suffering unspeakable anguish, pain, and terror of soul, on the cross but also earlier, has delivered me from hellish anguish and torment. This is why I can confess my Lord's suffering with confidence and not be afraid.",
      p:[{reference:"Matthew 27:46",text:"My God, my God, why hast thou forsaken me?"},{reference:"Isaiah 53:10",text:"Yet it pleased the LORD to bruise him; he hath put him to grief."}] },
    // Lord's Day 17
    { n:45, ld:"Lord's Day 17", lname:"The Resurrection",
      q:"How does Christ's resurrection benefit us?",
      a:"First, by his resurrection he has overcome death, so that he might make us share in the righteousness he won for us by his death. Second, by his power we too are already now resurrected to a new life. Third, Christ's resurrection is a guarantee of our glorious resurrection.",
      p:[{reference:"Romans 6:4",text:"Like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life."},{reference:"1 Corinthians 15:20",text:"Now is Christ risen from the dead, and become the firstfruits of them that slept."}] },
    // Lord's Day 18
    { n:46, ld:"Lord's Day 18", lname:"The Ascension",
      q:"What do you mean by saying: He ascended to heaven?",
      a:"That Christ, while his disciples watched, was lifted up from the earth to heaven and will be there for our good until he comes again to judge the living and the dead.",
      p:[{reference:"Acts 1:9",text:"And when he had spoken these things, while they beheld, he was taken up; and a cloud received him out of their sight."},{reference:"Hebrews 9:24",text:"For Christ is not entered into the holy places made with hands...but into heaven itself, now to appear in the presence of God for us."}] },
    { n:47, ld:"Lord's Day 18", lname:"The Ascension",
      q:"But isn't Christ with us until the end of the world as he promised us?",
      a:"Christ is true human and true God. In his human nature Christ is not now on earth; but in his divinity, majesty, grace, and Spirit he is not absent from us for a moment.",
      p:[{reference:"Matthew 28:20",text:"Lo, I am with you always, even unto the end of the world."},{reference:"John 14:18",text:"I will not leave you comfortless: I will come to you."}] },
    { n:48, ld:"Lord's Day 18", lname:"The Ascension",
      q:"If his humanity is not present wherever his divinity is, then aren't the two natures of Christ separated from each other?",
      a:"Certainly not. Since divinity is not limited and is present everywhere, it is evident that Christ's divinity is surely beyond the bounds of the humanity he has taken on, but at the same time his divinity is in and remains personally united to his humanity.",
      p:[{reference:"John 1:48",text:"Before that Philip called thee, when thou wast under the fig tree, I saw thee."},{reference:"Colossians 2:9",text:"For in him dwelleth all the fulness of the Godhead bodily."}] },
    { n:49, ld:"Lord's Day 18", lname:"The Ascension",
      q:"How does Christ's ascension to heaven benefit us?",
      a:"First, he pleads our cause in heaven in the presence of his Father. Second, we have our own flesh in heaven — a guarantee that Christ our head will take us, his members, to himself in heaven. Third, he sends his Spirit to us on earth as a further guarantee. By the Spirit's power we make the goal of our lives, not earthly things, but the things above where Christ is, sitting at God's right hand.",
      p:[{reference:"Romans 8:34",text:"Who is he that condemneth? It is Christ that died, yea rather, that is risen again, who is even at the right hand of God, who also maketh intercession for us."},{reference:"Colossians 3:1",text:"Seek those things which are above, where Christ sitteth on the right hand of God."}] },
    // Lord's Day 19
    { n:50, ld:"Lord's Day 19", lname:"Christ at God's Right Hand",
      q:"Why the next words: and is seated at the right hand of God?",
      a:"Christ ascended to heaven, there to show that he is head of his church, and that the Father rules all things through him.",
      p:[{reference:"Ephesians 1:20-22",text:"Which he wrought in Christ, when he raised him from the dead, and set him at his own right hand in the heavenly places, far above all principality, and power."},{reference:"Colossians 1:18",text:"He is the head of the body, the church."}] },
    { n:51, ld:"Lord's Day 19", lname:"Christ at God's Right Hand",
      q:"How does this glory of Christ our head benefit us?",
      a:"First, through his Holy Spirit he pours out his gifts from heaven upon us his members. Second, by his power he defends us and keeps us safe from all enemies.",
      p:[{reference:"Acts 2:33",text:"Being by the right hand of God exalted, and having received of the Father the promise of the Holy Ghost, he hath shed forth this."},{reference:"Psalm 2:9",text:"Thou shalt break them with a rod of iron; thou shalt dash them in pieces like a potter's vessel."}] },
    { n:52, ld:"Lord's Day 19", lname:"Christ at God's Right Hand",
      q:"How does Christ's return to judge the living and the dead comfort you?",
      a:"In all my distress and persecution I turn my eyes to the heavens and confidently await as judge the very One who has already stood trial in my place before God and so has removed the whole curse from me. Christ will cast all his enemies and mine into everlasting condemnation, but will take me and all his chosen ones to himself into the joy and the glory of heaven.",
      p:[{reference:"Romans 8:23-25",text:"We ourselves groan within ourselves, waiting for the adoption, to wit, the redemption of our body."},{reference:"Philippians 3:20",text:"Our conversation is in heaven; from whence also we look for the Saviour."}] },
    // Lord's Day 20
    { n:53, ld:"Lord's Day 20", lname:"The Holy Spirit",
      q:"What do you believe concerning the Holy Spirit?",
      a:"First, he, as well as the Father and the Son, is eternal God. Second, he has been given to me personally, so that, by true faith, he makes me share in Christ and all his blessings, comforts me, and remains with me forever.",
      p:[{reference:"John 14:16-17",text:"He shall give you another Comforter, that he may abide with you for ever; Even the Spirit of truth."},{reference:"1 Corinthians 6:19",text:"What? know ye not that your body is the temple of the Holy Ghost which is in you?"}] },
    // Lord's Day 21
    { n:54, ld:"Lord's Day 21", lname:"The Holy Catholic Church",
      q:"What do you believe concerning the holy catholic church?",
      a:"I believe that the Son of God through his Spirit and Word, out of the entire human race, from the beginning of the world to its end, gathers, protects, and preserves for himself a community chosen for eternal life and united in true faith. And of this community I am and always will be a living member.",
      p:[{reference:"John 10:11",text:"I am the good shepherd: the good shepherd giveth his life for the sheep."},{reference:"Acts 2:42",text:"They continued stedfastly in the apostles' doctrine and fellowship."}] },
    { n:55, ld:"Lord's Day 21", lname:"The Holy Catholic Church",
      q:"What do you understand by the communion of saints?",
      a:"First, that believers one and all, as members of this community, share in Christ and in all his treasures and gifts. Second, that each member should consider it a duty to use these gifts readily and cheerfully for the service and enrichment of the other members.",
      p:[{reference:"1 John 1:3",text:"That which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship is with the Father, and with his Son Jesus Christ."},{reference:"Romans 12:4-5",text:"As we have many members in one body...so we, being many, are one body in Christ."}] },
    { n:56, ld:"Lord's Day 21", lname:"The Holy Catholic Church",
      q:"What do you believe concerning the forgiveness of sins?",
      a:"I believe that God, because of Christ's atonement, will never hold against me any of my sins nor my sinful nature which I need to struggle against all my life. Rather, in his grace God grants me the righteousness of Christ to free me forever from judgment.",
      p:[{reference:"Psalm 103:3",text:"Who forgiveth all thine iniquities; who healeth all thy diseases."},{reference:"Micah 7:18-19",text:"Who is a God like unto thee, that pardoneth iniquity...he will have compassion upon us; he will subdue our iniquities."}] },
    // Lord's Day 22
    { n:57, ld:"Lord's Day 22", lname:"The Resurrection of the Body",
      q:"How does the resurrection of the body comfort you?",
      a:"Not only will my soul be taken immediately after this life to Christ its head, but even my very flesh, raised by the power of Christ, will be reunited with my soul and made like Christ's glorious body.",
      p:[{reference:"1 Corinthians 15:53",text:"For this corruptible must put on incorruption, and this mortal must put on immortality."},{reference:"Job 19:25-26",text:"For I know that my redeemer liveth...yet in my flesh shall I see God."}] },
    { n:58, ld:"Lord's Day 22", lname:"The Resurrection of the Body",
      q:"How does the article concerning life everlasting comfort you?",
      a:"Even as I already now experience in my heart the beginning of eternal joy, so after this life I will have perfect blessedness such as no eye has seen, no ear has heard, no human heart has ever imagined — a blessedness in which to praise God forever.",
      p:[{reference:"1 Corinthians 2:9",text:"Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him."},{reference:"John 17:3",text:"And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent."}] },
    // Lord's Day 23
    { n:59, ld:"Lord's Day 23", lname:"Justification by Faith",
      q:"What good does it do you, however, to believe all this?",
      a:"In Christ I am right with God and heir to life everlasting.",
      p:[{reference:"John 3:36",text:"He that believeth on the Son hath everlasting life."},{reference:"Romans 5:1",text:"Therefore being justified by faith, we have peace with God through our Lord Jesus Christ."}] },
    { n:60, ld:"Lord's Day 23", lname:"Justification by Faith",
      q:"How are you right with God?",
      a:"Only by true faith in Jesus Christ. Even though my conscience accuses me of having grievously sinned against all God's commandments and of never having kept any of them, and even though I am still inclined toward all evil, nevertheless, without my deserving it at all, out of sheer grace, God grants and credits to me the perfect satisfaction, righteousness, and holiness of Christ, as if I had never sinned nor been a sinner, as if I had been as perfectly obedient as Christ was obedient for me. All I need to do is to accept this gift of God with a believing heart.",
      p:[{reference:"Romans 3:21-24",text:"But now the righteousness of God without the law is manifested...through the redemption that is in Christ Jesus."},{reference:"2 Corinthians 5:21",text:"He hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him."}] },
    { n:61, ld:"Lord's Day 23", lname:"Justification by Faith",
      q:"Why do you say that by faith alone you are right with God?",
      a:"It is not because of any value my faith has that God is pleased with me. Only Christ's satisfaction, righteousness, and holiness make me right with God. And I can receive this righteousness and make it my own by faith alone.",
      p:[{reference:"Romans 3:28",text:"Therefore we conclude that a man is justified by faith without the deeds of the law."},{reference:"Ephesians 2:8-9",text:"For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works."}] },
    // Lord's Day 24
    { n:62, ld:"Lord's Day 24", lname:"Good Works",
      q:"Why can't the good works we do make us right with God, or at least help make us right with him?",
      a:"Because the righteousness which can pass God's judgment must be entirely perfect and must in every way measure up to the divine law. Even the best works we do in this life are imperfect and stained with sin.",
      p:[{reference:"Isaiah 64:6",text:"We are all as an unclean thing, and all our righteousnesses are as filthy rags."},{reference:"Galatians 3:10",text:"Cursed is every one that continueth not in all things which are written in the book of the law to do them."}] },
    { n:63, ld:"Lord's Day 24", lname:"Good Works",
      q:"How can you say that the good works we do don't earn anything when God promises to reward them in this life and the next?",
      a:"This reward is not earned; it is a gift of grace.",
      p:[{reference:"Luke 17:10",text:"So likewise ye, when ye shall have done all those things which are commanded you, say, We are unprofitable servants."},{reference:"Romans 11:6",text:"And if by grace, then is it no more of works: otherwise grace is no more grace."}] },
    { n:64, ld:"Lord's Day 24", lname:"Good Works",
      q:"But doesn't this teaching make people indifferent and wicked?",
      a:"No. It is impossible for those grafted into Christ by true faith not to produce fruits of gratitude.",
      p:[{reference:"Romans 6:1-2",text:"Shall we continue in sin, that grace may abound? God forbid. How shall we, that are dead to sin, live any longer therein?"},{reference:"John 15:5",text:"He that abideth in me, and I in him, the same bringeth forth much fruit."}] },
    // Lord's Day 25
    { n:65, ld:"Lord's Day 25", lname:"The Sacraments",
      q:"It is by faith alone that we share in Christ and all his blessings: where then does that faith come from?",
      a:"The Holy Spirit produces it in our hearts by the preaching of the holy gospel, and confirms it through our use of the holy sacraments.",
      p:[{reference:"Romans 10:17",text:"Faith cometh by hearing, and hearing by the word of God."},{reference:"1 Corinthians 1:21",text:"It pleased God by the foolishness of preaching to save them that believe."}] },
    { n:66, ld:"Lord's Day 25", lname:"The Sacraments",
      q:"What are sacraments?",
      a:"Sacraments are holy signs and seals for us to see. They were instituted by God so that by our use of them he might make us understand more clearly the promise of the gospel, and might put his seal on that promise. And this is God's gospel promise: to forgive our sins and give us eternal life by grace alone because of Christ's one sacrifice finished on the cross.",
      p:[{reference:"Genesis 17:11",text:"And ye shall circumcise the flesh of your foreskin; and it shall be a token of the covenant betwixt me and you."},{reference:"Romans 4:11",text:"He received the sign of circumcision, a seal of the righteousness of the faith."}] },
    { n:67, ld:"Lord's Day 25", lname:"The Sacraments",
      q:"Are both the word and the sacraments then intended to focus our faith on the sacrifice of Jesus Christ on the cross as the only ground of our salvation?",
      a:"Right! In the gospel the Holy Spirit teaches us and through the holy sacraments he assures us that our entire salvation rests on Christ's one sacrifice for us on the cross.",
      p:[{reference:"Romans 6:3",text:"Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?"},{reference:"1 Corinthians 11:26",text:"For as often as ye eat this bread, and drink this cup, ye do shew the Lord's death till he come."}] },
    { n:68, ld:"Lord's Day 25", lname:"The Sacraments",
      q:"How many sacraments did Christ institute in the New Testament?",
      a:"Two: holy baptism and the holy supper.",
      p:[{reference:"Matthew 28:19",text:"Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost."},{reference:"Matthew 26:26-28",text:"And as they were eating, Jesus took bread, and blessed it, and brake it, and gave it to the disciples, and said, Take, eat; this is my body."}] },
    // Lord's Day 26
    { n:69, ld:"Lord's Day 26", lname:"Baptism",
      q:"How does baptism remind you and assure you that Christ's one sacrifice on the cross is for you personally?",
      a:"In this way: Christ instituted this outward washing and with it gave the promise that, as surely as water washes away the dirt from the body, so certainly his blood and his Spirit wash away my soul's impurity, in other words, all my sins.",
      p:[{reference:"Acts 2:38",text:"Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins."},{reference:"Romans 6:3-4",text:"Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?"}] },
    { n:70, ld:"Lord's Day 26", lname:"Baptism",
      q:"What does it mean to be washed with Christ's blood and Spirit?",
      a:"To be washed with Christ's blood means that God, by grace, has forgiven my sins because of Christ's blood poured out for me in his sacrifice on the cross. To be washed with Christ's Spirit means that the Holy Spirit has renewed me and set me apart to be a member of Christ so that more and more I become dead to sin and increasingly live a holy and blameless life.",
      p:[{reference:"Hebrews 12:24",text:"To Jesus the mediator of the new covenant, and to the blood of sprinkling."},{reference:"John 1:33",text:"He which baptizeth with the Holy Ghost."}] },
    { n:71, ld:"Lord's Day 26", lname:"Baptism",
      q:"Where does Christ promise that we are washed with his blood and Spirit as surely as we are washed with the water of baptism?",
      a:"In the institution of baptism where he says: Whoever believes and is baptized will be saved; but whoever does not believe will be condemned. This promise is repeated when Scripture calls baptism the washing of rebirth and the washing away of sins.",
      p:[{reference:"Mark 16:16",text:"He that believeth and is baptized shall be saved; but he that believeth not shall be damned."},{reference:"Titus 3:5",text:"The washing of regeneration, and renewing of the Holy Ghost."}] },
    // Lord's Day 27
    { n:72, ld:"Lord's Day 27", lname:"Baptism Continued",
      q:"Does this outward washing with water itself wash away sins?",
      a:"No, only Jesus Christ's blood and the Holy Spirit cleanse us from all sins.",
      p:[{reference:"Matthew 3:11",text:"I indeed baptize you with water unto repentance: but he that cometh after me is mightier than I...he shall baptize you with the Holy Ghost, and with fire."},{reference:"1 Peter 3:21",text:"The like figure whereunto even baptism doth also now save us...not the putting away of the filth of the flesh, but the answer of a good conscience toward God, by the resurrection of Jesus Christ."}] },
    { n:73, ld:"Lord's Day 27", lname:"Baptism Continued",
      q:"Why then does the Holy Spirit call baptism the washing of rebirth and the washing away of sins?",
      a:"God has good reasons for these words. He wants to teach us that the blood and Spirit of Christ wash away our sins just as water washes away dirt from our bodies. But more importantly, he wants to assure us, by this divine pledge and sign, that the washing away of our sins spiritually is as real as physical washing with water.",
      p:[{reference:"Galatians 3:27",text:"For as many of you as have been baptized into Christ have put on Christ."},{reference:"Colossians 2:11-12",text:"In whom also ye are circumcised with the circumcision made without hands...buried with him in baptism, wherein also ye are risen with him."}] },
    { n:74, ld:"Lord's Day 27", lname:"Baptism Continued",
      q:"Should infants also be baptized?",
      a:"Yes. Infants as well as adults are in God's covenant and are his people. They, no less than adults, are promised the forgiveness of sin through Christ's blood and the Holy Spirit who produces faith. Therefore, by baptism, the mark of the covenant, infants should be received into the Christian church and should be distinguished from the children of unbelievers. This was done in the Old Testament by circumcision, which was replaced in the New Testament by baptism.",
      p:[{reference:"Genesis 17:7",text:"And I will establish my covenant between me and thee and thy seed after thee in their generations for an everlasting covenant."},{reference:"Acts 2:38-39",text:"Repent, and be baptized every one of you...For the promise is unto you, and to your children."}] },
    // Lord's Day 28
    { n:75, ld:"Lord's Day 28", lname:"The Lord's Supper",
      q:"How does the holy supper remind you and assure you that you share in Christ's one sacrifice on the cross and in all his gifts?",
      a:"In this way: Christ has commanded me and all believers to eat this broken bread and to drink this cup. With these commands he gave this promise: As surely as I see with my eyes the bread of the Lord broken for me and the cup given to me, so surely his body was offered and broken for me and his blood poured out for me on the cross. As surely as I receive from the hand of the one who serves, and taste with my mouth the bread and cup of the Lord, given me as sure signs of Christ's body and blood, so surely he nourishes and refreshes my soul for eternal life with his crucified body and poured-out blood.",
      p:[{reference:"1 Corinthians 11:23-26",text:"The Lord Jesus the same night in which he was betrayed took bread: And when he had given thanks, he brake it, and said, Take, eat: this is my body, which is broken for you."}] },
    { n:76, ld:"Lord's Day 28", lname:"The Lord's Supper",
      q:"What does it mean to eat the crucified body of Christ and to drink his poured-out blood?",
      a:"It means to accept with a believing heart the entire suffering and death of Christ and thereby to receive forgiveness of sins and eternal life. It means, furthermore, to be so united with Christ that he dwells in us and we in him. We are as certainly nourished and refreshed by the sacred body and blood of Christ for the life everlasting as we receive the holy bread and cup of the Lord, in remembrance of him.",
      p:[{reference:"John 6:35",text:"I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst."},{reference:"John 6:53-56",text:"Except ye eat the flesh of the Son of man, and drink his blood, ye have no life in you."}] },
    { n:77, ld:"Lord's Day 28", lname:"The Lord's Supper",
      q:"Where does Christ promise to nourish and refresh believers with his body and blood as surely as they eat this broken bread and drink this cup?",
      a:"In the institution of the Lord's Supper: The Lord Jesus, on the night he was betrayed, took bread, and when he had given thanks, he broke it and said, This is my body, which is for you; do this in remembrance of me. In the same way, after supper he took the cup, saying, This cup is the new covenant in my blood; do this, whenever you drink it, in remembrance of me. For whenever you eat this bread and drink this cup, you proclaim the Lord's death until he comes.",
      p:[{reference:"1 Corinthians 11:23-25",text:"The Lord Jesus the same night in which he was betrayed took bread: And when he had given thanks, he brake it."},{reference:"Matthew 26:26-28",text:"This is my body...this is my blood of the new testament, which is shed for many for the remission of sins."}] },
    // Lord's Day 29
    { n:78, ld:"Lord's Day 29", lname:"The Body and Blood of Christ",
      q:"Are the bread and wine changed into the real body and blood of Christ?",
      a:"No. Just as the water of baptism is not changed into Christ's blood and does not itself wash away sins but is simply God's sign and assurance, so too the bread of the Lord's Supper is not changed into the actual body of Christ even though it is called the body of Christ in keeping with the nature and language of sacraments.",
      p:[{reference:"1 Corinthians 11:26-28",text:"For as often as ye eat this bread, and drink this cup, ye do shew the Lord's death till he come."},{reference:"Matthew 26:29",text:"I will not drink henceforth of this fruit of the vine, until that day when I drink it new with you in my Father's kingdom."}] },
    { n:79, ld:"Lord's Day 29", lname:"The Body and Blood of Christ",
      q:"Why then does Christ call the bread his body and the cup his blood, or the new covenant in his blood?",
      a:"He speaks this way for a good reason: He wants to teach us by his supper that as bread and wine nourish our temporal life, so too his crucified body and poured-out blood truly nourish our souls for eternal life. But more importantly, he wants to assure us, by this visible sign and pledge, that we, through the Holy Spirit's work, share in his true body and blood as surely as our mouths receive these holy signs in his remembrance, and that all of his suffering and obedience are as definitely ours as if we personally had suffered and paid for our sins.",
      p:[{reference:"John 6:55-56",text:"For my flesh is meat indeed, and my blood is drink indeed. He that eateth my flesh, and drinketh my blood, dwelleth in me, and I in him."}] },
    // Lord's Day 30
    { n:80, ld:"Lord's Day 30", lname:"The Lord's Supper and the Mass",
      q:"How does the Lord's Supper differ from the Roman Catholic Mass?",
      a:"The Lord's Supper declares to us that our sins have been completely forgiven through the one sacrifice of Jesus Christ which he himself finished on the cross once and for all. It also declares to us that the Holy Spirit grafts us into Christ, who with his very body is now in heaven at the right hand of the Father where he wants us to worship him.",
      p:[{reference:"Hebrews 9:12",text:"By his own blood he entered in once into the holy place, having obtained eternal redemption for us."},{reference:"Hebrews 10:12-14",text:"This man, after he had offered one sacrifice for sins for ever, sat down on the right hand of God."}] },
    { n:81, ld:"Lord's Day 30", lname:"The Lord's Supper and the Mass",
      q:"Who are to come to the Lord's table?",
      a:"Those who are displeased with themselves because of their sins, but who nevertheless trust that their sins are pardoned and that their continuing weakness is covered by the suffering and death of Christ, and who also desire more and more to strengthen their faith and to lead a better life. Hypocrites and those who are unrepentant, however, eat and drink judgment on themselves.",
      p:[{reference:"1 Corinthians 10:19-22",text:"Are we stronger than he?"},{reference:"1 Corinthians 11:28-29",text:"But let a man examine himself, and so let him eat of that bread, and drink of that cup."}] },
    { n:82, ld:"Lord's Day 30", lname:"The Lord's Supper and the Mass",
      q:"Are those to be admitted to the Lord's Supper who show by what they profess and how they live that they are unbelieving and ungodly?",
      a:"No, that would dishonor God's covenant and bring down God's anger upon the entire congregation. Therefore, according to the instruction of Christ and his apostles, the Christian church is duty-bound to exclude such people, by the official use of the keys of the kingdom, until they reform their lives.",
      p:[{reference:"1 Corinthians 11:27-32",text:"Whosoever shall eat this bread, and drink this cup of the Lord, unworthily, shall be guilty of the body and blood of the Lord."},{reference:"Matthew 18:17",text:"If he neglect to hear them, tell it unto the church: but if he neglect to hear the church, let him be unto thee as an heathen man."}] },
    // Lord's Day 31
    { n:83, ld:"Lord's Day 31", lname:"The Keys of the Kingdom",
      q:"What are the keys of the kingdom?",
      a:"The preaching of the holy gospel and Christian discipline toward repentance. Both preaching and discipline open the kingdom of heaven to believers and close it to unbelievers.",
      p:[{reference:"Matthew 16:19",text:"And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven."},{reference:"John 20:22-23",text:"And when he had said this, he breathed on them, and saith unto them, Receive ye the Holy Ghost: Whose soever sins ye remit, they are remitted unto them."}] },
    { n:84, ld:"Lord's Day 31", lname:"The Keys of the Kingdom",
      q:"How does preaching the holy gospel open and close the kingdom of heaven?",
      a:"According to the command of Christ: The kingdom of heaven is opened by proclaiming and publicly declaring to all believers, each and every one, that, as often as they accept the gospel promise in true faith, God, because of what Christ has done, has truly forgiven all their sins. The kingdom of heaven is closed, however, by proclaiming and publicly declaring to unbelievers and hypocrites that, as long as they do not repent, the anger of God and eternal condemnation rest on them. God's judgment, both in this life and in the life to come, is based on this gospel testimony.",
      p:[{reference:"Matthew 16:19",text:"Whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven."},{reference:"John 3:18",text:"He that believeth on him is not condemned: but he that believeth not is condemned already."}] },
    { n:85, ld:"Lord's Day 31", lname:"The Keys of the Kingdom",
      q:"How is the kingdom of heaven closed and opened by Christian discipline?",
      a:"According to the command of Christ: If anyone, though called a Christian, professes unchristian teachings or lives an unchristian life, and after repeated and loving counsel, refuses to abandon his errors and wickedness, and after being reported to the church, that is, to its officers, fails to respond also to their admonition — such a person is excluded from the Christian fellowship by their refusal of the sacraments, and by God himself from the kingdom of Christ. Such a person, when he promises and demonstrates genuine reform, is received again as a member of Christ and of his church.",
      p:[{reference:"Matthew 18:15-18",text:"Moreover if thy brother shall trespass against thee, go and tell him his fault between thee and him alone."},{reference:"1 Corinthians 5:11",text:"But now I have written unto you not to keep company, if any man that is called a brother be a fornicator."}] },
    // Lord's Day 32
    { n:86, ld:"Lord's Day 32", lname:"Good Works and Gratitude",
      q:"We have been delivered from our misery by God's grace alone through Christ and not because we have earned it: why then must we still do good?",
      a:"To be sure, Christ has redeemed us by his blood. But we do good because Christ by his Spirit is also renewing us to be like himself, so that in all our living we may show that we are thankful to God for all he has done for us, and so that he may be praised through us. And we do good so that we may be assured of our faith by its fruits, and so that by our godly living our neighbors may be won over to Christ.",
      p:[{reference:"Romans 6:13",text:"Neither yield ye your members as instruments of unrighteousness unto sin: but yield yourselves unto God."},{reference:"1 Peter 2:12",text:"Having your conversation honest among the Gentiles: that...they may by your good works, which they shall behold, glorify God."}] },
    { n:87, ld:"Lord's Day 32", lname:"Good Works and Gratitude",
      q:"Can those be saved who do not turn to God from their ungrateful and impenitent ways?",
      a:"By no means. Scripture tells us that no unchaste person, no idolater, adulterer, thief, no covetous person, no drunkard, slanderer, robber, or the like is going to inherit the kingdom of God.",
      p:[{reference:"1 Corinthians 6:9-10",text:"Know ye not that the unrighteous shall not inherit the kingdom of God? Be not deceived: neither fornicators, nor idolaters, nor adulterers...shall inherit the kingdom of God."},{reference:"Galatians 5:19-21",text:"The works of the flesh are manifest, which are these; Adultery, fornication, uncleanness...they which do such things shall not inherit the kingdom of God."}] },
    // Lord's Day 33
    { n:88, ld:"Lord's Day 33", lname:"True Repentance",
      q:"What is involved in genuine repentance or conversion?",
      a:"Two things: the dying-away of the old self, and the coming-to-life of the new.",
      p:[{reference:"Romans 6:4-6",text:"We are buried with him by baptism into death: that like as Christ was raised up from the dead...even so we also should walk in newness of life."},{reference:"Ephesians 4:22-24",text:"Put off concerning the former conversation the old man...And be renewed in the spirit of your mind."}] },
    { n:89, ld:"Lord's Day 33", lname:"True Repentance",
      q:"What is the dying-away of the old self?",
      a:"It is to be genuinely sorry for sin, to hate it more and more, and to run away from it.",
      p:[{reference:"Psalm 51:3-4",text:"For I acknowledge my transgressions: and my sin is ever before me. Against thee, thee only, have I sinned."},{reference:"Joel 2:13",text:"Rend your heart, and not your garments, and turn unto the LORD your God."}] },
    { n:90, ld:"Lord's Day 33", lname:"True Repentance",
      q:"What is the coming-to-life of the new self?",
      a:"It is wholehearted joy in God through Christ and a strong desire to live according to the will of God in all good works.",
      p:[{reference:"Psalm 51:8",text:"Make me to hear joy and gladness; that the bones which thou hast broken may rejoice."},{reference:"Romans 5:1",text:"Therefore being justified by faith, we have peace with God through our Lord Jesus Christ."}] },
    { n:91, ld:"Lord's Day 33", lname:"True Repentance",
      q:"What do we do that is good?",
      a:"Only that which arises out of true faith, conforms to God's law, and is done for his glory; and not that which is based on what we think is right or on established human tradition.",
      p:[{reference:"1 Corinthians 10:31",text:"Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God."},{reference:"Romans 14:23",text:"Whatsoever is not of faith is sin."}] },
    // Lord's Day 34
    { n:92, ld:"Lord's Day 34", lname:"The Ten Commandments",
      q:"What does the Lord say in his law?",
      a:"God spoke all these words: I am the LORD your God, who brought you out of Egypt, out of the land of slavery. You shall have no other gods before me. You shall not make for yourself an image...You shall not misuse the name of the LORD your God...Remember the Sabbath day by keeping it holy...Honor your father and your mother...You shall not murder. You shall not commit adultery. You shall not steal. You shall not give false testimony against your neighbor. You shall not covet...",
      p:[{reference:"Exodus 20:1-17",text:"And God spake all these words, saying, I am the LORD thy God, which have brought thee out of the land of Egypt, out of the house of bondage. Thou shalt have no other gods before me."}] },
    { n:93, ld:"Lord's Day 34", lname:"The Ten Commandments",
      q:"How are these commandments divided?",
      a:"Into two tables. The first has four commandments, teaching us what our relation to God should be. The second has six commandments, teaching us what we owe our neighbor.",
      p:[{reference:"Matthew 22:37-39",text:"Thou shalt love the Lord thy God with all thy heart...Thou shalt love thy neighbour as thyself."}] },
    { n:94, ld:"Lord's Day 34", lname:"The Ten Commandments",
      q:"What does the Lord require in the first commandment?",
      a:"That I, not wanting to endanger my very salvation, avoid and shun all idolatry, magic, superstitious rites, and prayer to saints or to other creatures. That I sincerely acknowledge the only true God, trust him alone, look to him for every good thing humbly and patiently, love him, fear him, and honor him with all my heart. In short, that I give up anything rather than go against his will in any way.",
      p:[{reference:"1 Corinthians 8:5-6",text:"For though there be that are called gods, whether in heaven or in earth...But to us there is but one God, the Father."},{reference:"Matthew 4:10",text:"Thou shalt worship the Lord thy God, and him only shalt thou serve."}] },
    { n:95, ld:"Lord's Day 35", lname:"The First and Second Commandments",
      q:"What is idolatry?",
      a:"Idolatry is having or inventing something in which one trusts in place of or alongside of the only true God, who has revealed himself in the Word.",
      p:[{reference:"1 Chronicles 16:26",text:"For all the gods of the people are idols: but the LORD made the heavens."},{reference:"Galatians 4:8",text:"Howbeit then, when ye knew not God, ye did service unto them which by nature are no gods."}] },
    { n:96, ld:"Lord's Day 35", lname:"The First and Second Commandments",
      q:"What is God's will for us in the second commandment?",
      a:"That we in no way make any image of God nor worship him in any other way than has been commanded in God's Word.",
      p:[{reference:"Deuteronomy 4:15-16",text:"Take ye therefore good heed unto yourselves...Lest ye corrupt yourselves, and make you a graven image."},{reference:"Isaiah 46:5",text:"To whom will ye liken me, and make me equal, and compare me, that we may be like?"}] },
    { n:97, ld:"Lord's Day 35", lname:"The First and Second Commandments",
      q:"May we then not make any image at all?",
      a:"God can not and may not be visibly portrayed in any way. Although creatures may be portrayed, yet God forbids making or having such images if one's intention is to worship them or to serve God through them.",
      p:[{reference:"Exodus 34:13-14",text:"But ye shall destroy their altars, break their images, and cut down their groves: For thou shalt worship no other god."},{reference:"Acts 17:29",text:"We ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man's device."}] },
    { n:98, ld:"Lord's Day 35", lname:"The First and Second Commandments",
      q:"But may not images be permitted in the churches as teaching aids for the unlearned?",
      a:"No, we shouldn't try to be wiser than God. He wants his people instructed by the living preaching of his Word — not by idols that cannot even talk.",
      p:[{reference:"Romans 10:14-15",text:"How then shall they call on him in whom they have not believed? and how shall they believe in him of whom they have not heard?"},{reference:"Jeremiah 10:8",text:"But they are altogether brutish and foolish: the stock is a doctrine of vanities."}] },
    // Lord's Day 36
    { n:99, ld:"Lord's Day 36", lname:"The Third Commandment",
      q:"What is God's will for us in the third commandment?",
      a:"That we neither blaspheme nor misuse the name of God by cursing, perjury, or unnecessary oaths, nor share in such horrible sins by being silent bystanders. In a word, it requires that we use the holy name of God only with reverence and awe, so that we may properly confess him, pray to him, and praise him in everything we do and say.",
      p:[{reference:"Leviticus 24:15-16",text:"Whosoever curseth his God shall bear his sin. And he that blasphemeth the name of the LORD, he shall surely be put to death."},{reference:"Matthew 5:37",text:"Let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil."}] },
    { n:100, ld:"Lord's Day 36", lname:"The Third Commandment",
      q:"Is blasphemy of God's name by swearing and cursing really such serious sin that God is angry also with those who do not do all they can to help prevent and forbid it?",
      a:"Yes, indeed. No sin is greater, no sin makes God more angry than blaspheming his name. That is why he commanded the death penalty for it.",
      p:[{reference:"Leviticus 5:1",text:"And if a soul sin, and hear the voice of swearing, and is a witness, whether he hath seen or known of it; if he do not utter it, then he shall bear his iniquity."},{reference:"Proverbs 29:24",text:"Whoso is partner with a thief hateth his own soul: he heareth cursing, and bewrayeth it not."}] },
    // Lord's Day 37
    { n:101, ld:"Lord's Day 37", lname:"Oaths and Vows",
      q:"May we swear an oath in God's name if we do it reverently?",
      a:"Yes, when the government demands it, or when necessity requires it, in order to maintain and promote truth and trustworthiness for God's glory and our neighbor's good. Such oaths are grounded in God's Word and were rightly used by the people of God in the Old and New Testaments.",
      p:[{reference:"Deuteronomy 6:13",text:"Thou shalt fear the LORD thy God, and serve him, and shalt swear by his name."},{reference:"Hebrews 6:16",text:"For men verily swear by the greater: and an oath for confirmation is to them an end of all strife."}] },
    { n:102, ld:"Lord's Day 37", lname:"Oaths and Vows",
      q:"May we also swear by saints or other creatures?",
      a:"No. A legitimate oath means calling upon God as the one who knows my heart to witness to my truthfulness and to punish me if I swear falsely. No creature is worthy of such honor.",
      p:[{reference:"Matthew 5:34-37",text:"Swear not at all; neither by heaven...nor by the earth...But let your communication be, Yea, yea; Nay, nay."},{reference:"Revelation 5:13",text:"Blessing, and honour, and glory, and power, be unto him that sitteth upon the throne, and unto the Lamb for ever and ever."}] },
    // Lord's Day 38
    { n:103, ld:"Lord's Day 38", lname:"The Fourth Commandment",
      q:"What is God's will for you in the fourth commandment?",
      a:"First, that the gospel ministry and education for it be maintained, and that, especially on the festive day of rest, I regularly attend the assembly of God's people to learn what God's Word teaches, to participate in the sacraments, to pray to God publicly, and to bring Christian offerings for the poor. Second, that every day of my life I rest from my evil ways, let the Lord work in me through his Spirit, and so begin already in this life the eternal Sabbath.",
      p:[{reference:"Psalm 92:1-2",text:"It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O Most High: To shew forth thy lovingkindness in the morning."},{reference:"Revelation 14:13",text:"Blessed are the dead which die in the Lord from henceforth: Yea, saith the Spirit, that they may rest from their labours."}] },
    // Lord's Day 39
    { n:104, ld:"Lord's Day 39", lname:"The Fifth Commandment",
      q:"What is God's will for you in the fifth commandment?",
      a:"That I honor, love, and be loyal to my father and mother and all those in authority over me; that I obey and submit to them, as is proper, when they correct and punish me; and also that I be patient with their failings — for through them God chooses to rule us.",
      p:[{reference:"Ephesians 6:1-3",text:"Children, obey your parents in the Lord: for this is right. Honour thy father and mother; which is the first commandment with promise."},{reference:"Romans 13:1",text:"Let every soul be subject unto the higher powers. For there is no power but of God."}] },
    // Lord's Day 40
    { n:105, ld:"Lord's Day 40", lname:"The Sixth Commandment",
      q:"What is God's will for you in the sixth commandment?",
      a:"I am not to belittle, insult, hate, or kill my neighbor — not by my thoughts, my words, my look or gesture, and certainly not by actual deeds — and I am not to be party to this in others; rather, I am to put away all desire for revenge. I am not to harm or recklessly endanger myself either. Prevention of murder is also why the government is armed with the sword.",
      p:[{reference:"Matthew 5:21-22",text:"Ye have heard that it was said by them of old time, Thou shalt not kill; and whosoever shall kill shall be in danger of the judgment: But I say unto you, That whosoever is angry with his brother without a cause shall be in danger of the judgment."},{reference:"Romans 12:19",text:"Dearly beloved, avenge not yourselves, but rather give place unto wrath: for it is written, Vengeance is mine; I will repay, saith the Lord."}] },
    { n:106, ld:"Lord's Day 40", lname:"The Sixth Commandment",
      q:"Does this commandment refer only to killing?",
      a:"By forbidding murder God teaches us that he hates the root of murder: envy, hatred, anger, vindictiveness. In God's sight all such are murder.",
      p:[{reference:"1 John 3:15",text:"Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him."},{reference:"Proverbs 14:30",text:"A sound heart is the life of the flesh: but envy the rottenness of the bones."}] },
    { n:107, ld:"Lord's Day 40", lname:"The Sixth Commandment",
      q:"Is it enough then that we do not kill our neighbor in any such way?",
      a:"No. By condemning envy, hatred, and anger God tells us to love our neighbors as ourselves, to be patient, peace-loving, gentle, merciful, and friendly to them, to protect them from harm as much as we can, and to do good even to our enemies.",
      p:[{reference:"Matthew 5:44-45",text:"Love your enemies, bless them that curse you, do good to them that hate you."},{reference:"Romans 12:10",text:"Be kindly affectioned one to another with brotherly love; in honour preferring one another."}] },
    // Lord's Day 41
    { n:108, ld:"Lord's Day 41", lname:"The Seventh Commandment",
      q:"What is God's will for us in the seventh commandment?",
      a:"God condemns all unchastity. We should therefore thoroughly detest it and, married or single, live decent and chaste lives.",
      p:[{reference:"1 Corinthians 6:18-20",text:"Flee fornication...What? know ye not that your body is the temple of the Holy Ghost...therefore glorify God in your body."},{reference:"Hebrews 13:4",text:"Marriage is honourable in all, and the bed undefiled: but whoremongers and adulterers God will judge."}] },
    { n:109, ld:"Lord's Day 41", lname:"The Seventh Commandment",
      q:"Does God, in this commandment, forbid only such scandalous sins as adultery?",
      a:"We are temples of the Holy Spirit, body and soul, and God wants both to be kept clean and holy. That is why he forbids everything which incites unchastity, whether it be actions, looks, talk, thoughts, or desires.",
      p:[{reference:"Matthew 5:27-28",text:"Ye have heard that it was said by them of old time, Thou shalt not commit adultery: But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart."},{reference:"Ephesians 5:3-4",text:"Fornication, and all uncleanness, or covetousness, let it not be once named among you...Nor filthiness, nor foolish talking."}] },
    // Lord's Day 42
    { n:110, ld:"Lord's Day 42", lname:"The Eighth Commandment",
      q:"What does God forbid in the eighth commandment?",
      a:"He forbids not only outright theft and robbery, punishable by law. But in God's sight theft also includes all scheming and swindling in order to get our neighbor's goods for ourselves, whether by force or means that appear legitimate, such as: inaccurate measurements of weight, size, or volume; fraudulent merchandising; counterfeit money; excessive interest; or any other means forbidden by God. In addition God forbids all greed and pointless squandering of his gifts.",
      p:[{reference:"1 Corinthians 6:10",text:"Nor thieves, nor covetous, nor drunkards, nor revilers, nor extortioners, shall inherit the kingdom of God."},{reference:"Luke 3:14",text:"And the soldiers likewise demanded of him, saying, And what shall we do? And he said unto them, Do violence to no man, neither accuse any falsely; and be content with your wages."}] },
    { n:111, ld:"Lord's Day 42", lname:"The Eighth Commandment",
      q:"What does God require of you in this commandment?",
      a:"That I do whatever I can for my neighbor's good, that I treat others as I would like them to treat me, and that I work faithfully so that I may share with those in need.",
      p:[{reference:"Matthew 7:12",text:"Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets."},{reference:"Ephesians 4:28",text:"Let him that stole steal no more: but rather let him labour, working with his hands the thing which is good, that he may have to give to him that needeth."}] },
    // Lord's Day 43
    { n:112, ld:"Lord's Day 43", lname:"The Ninth Commandment",
      q:"What is God's will for us in the ninth commandment?",
      a:"God's will is that I never give false testimony against anyone, twist no one's words, not gossip or slander, nor join in condemning anyone without a hearing or without a just cause. Rather, in court and everywhere else, I should avoid lying and deceit of every kind; these are devices the devil himself uses, and they would call down on me God's intense anger. I should love the truth, speak it candidly, and openly acknowledge it. And I should do what I can to guard and advance my neighbor's good name.",
      p:[{reference:"Proverbs 19:5",text:"A false witness shall not be unpunished, and he that speaketh lies shall not escape."},{reference:"Ephesians 4:25",text:"Wherefore putting away lying, speak every man truth with his neighbour: for we are members one of another."}] },
    // Lord's Day 44
    { n:113, ld:"Lord's Day 44", lname:"The Tenth Commandment",
      q:"What is God's will for us in the tenth commandment?",
      a:"That not even the slightest thought or desire contrary to any one of God's commandments should ever arise in our hearts. Rather, with all our hearts we should always hate sin and take pleasure in whatever is right.",
      p:[{reference:"Romans 7:7",text:"I had not known lust, except the law had said, Thou shalt not covet."},{reference:"Psalm 19:14",text:"Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer."}] },
    { n:114, ld:"Lord's Day 44", lname:"The Tenth Commandment",
      q:"But can those converted to God obey these commandments perfectly?",
      a:"No. In this life even the holiest have only a small beginning of this obedience. Nevertheless, with all seriousness of purpose, they do begin to live according to all, not only some, of God's commandments.",
      p:[{reference:"Ecclesiastes 7:20",text:"For there is not a just man upon earth, that doeth good, and sinneth not."},{reference:"Romans 7:14-15",text:"We know that the law is spiritual: but I am carnal, sold under sin. For that which I do I allow not."}] },
    { n:115, ld:"Lord's Day 44", lname:"The Tenth Commandment",
      q:"Since no one in this life can obey the Ten Commandments perfectly, why does God want them preached so pointedly?",
      a:"First, so that the longer we live the more we may come to know our sinfulness and the more eagerly look to Christ for forgiveness of sins and righteousness. Second, so that we may never stop striving, and never stop praying to God for the grace of the Holy Spirit, to be renewed more and more after God's image, until after this life we reach our goal: perfection.",
      p:[{reference:"Romans 3:20",text:"By the law is the knowledge of sin."},{reference:"1 John 1:8-9",text:"If we say that we have no sin, we deceive ourselves, and the truth is not in us. If we confess our sins, he is faithful and just to forgive us our sins."}] },
    // Lord's Day 45
    { n:116, ld:"Lord's Day 45", lname:"Prayer",
      q:"Why do Christians need to pray?",
      a:"Because prayer is the most important part of the thankfulness God requires of us. And also because God gives his grace and Holy Spirit only to those who pray continually and groan inwardly, asking God for these gifts and thanking him for them.",
      p:[{reference:"Psalm 50:14-15",text:"Offer unto God thanksgiving; and pay thy vows unto the most High: And call upon me in the day of trouble: I will deliver thee, and thou shalt glorify me."},{reference:"Matthew 7:7",text:"Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you."}] },
    { n:117, ld:"Lord's Day 45", lname:"Prayer",
      q:"How does God want us to pray so that he will listen to us?",
      a:"First, we must pray from the heart to no other than the one true God, who has revealed himself to us in his Word, asking for everything he has commanded us to ask for. Second, we must acknowledge our need and misery, hiding nothing, and humble ourselves in his majestic presence. Third, we must rest on this unshakable foundation: even though we do not deserve it, God will surely listen to our prayer because of Christ our Lord. That is what he promised us in his Word.",
      p:[{reference:"John 4:22-24",text:"Ye worship ye know not what: we know what we worship: for salvation is of the Jews. But the hour cometh...when the true worshippers shall worship the Father in spirit and in truth."},{reference:"Romans 10:13",text:"For whosoever shall call upon the name of the Lord shall be saved."}] },
    { n:118, ld:"Lord's Day 45", lname:"Prayer",
      q:"What did God command us to pray for?",
      a:"Everything we need, spiritually and physically, as embraced in the prayer Christ our Lord himself taught us.",
      p:[{reference:"James 1:17",text:"Every good gift and every perfect gift is from above, and cometh down from the Father of lights."},{reference:"Matthew 6:33",text:"But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."}] },
    { n:119, ld:"Lord's Day 45", lname:"Prayer",
      q:"What is this prayer?",
      a:"Our Father in heaven, hallowed be your name, your kingdom come, your will be done on earth as it is in heaven. Give us today our daily bread. Forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from the evil one. For the kingdom and the power and the glory are yours now and forever. Amen.",
      p:[{reference:"Matthew 6:9-13",text:"After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name..."},{reference:"Luke 11:2-4",text:"And he said unto them, When ye pray, say, Our Father which art in heaven, Hallowed be thy name."}] },
    // Lord's Day 46
    { n:120, ld:"Lord's Day 46", lname:"Our Father in Heaven",
      q:"Why did Christ command us to call God 'our Father'?",
      a:"At the very beginning of our prayer Christ wants to kindle in us what is basic to our prayer — the childlike awe and trust that God through Christ has become our Father. Our fathers do not refuse us the things of this life; God our Father will even less refuse to give us what we ask in faith.",
      p:[{reference:"Matthew 7:9-11",text:"What man is there of you, whom if his son ask bread, will he give him a stone?...how much more shall your Father which is in heaven give good things to them that ask him?"},{reference:"Luke 11:11-13",text:"If a son shall ask bread of any of you that is a father, will he give him a stone?...how much more shall your heavenly Father give the Holy Spirit to them that ask him?"}] },
    { n:121, ld:"Lord's Day 46", lname:"Our Father in Heaven",
      q:"Why the words 'in heaven'?",
      a:"These words teach us not to think of God's heavenly majesty as something earthly, and to expect everything for body and soul from his almighty power.",
      p:[{reference:"Jeremiah 23:24",text:"Can any hide himself in secret places that I shall not see him? saith the LORD. Do not I fill heaven and earth? saith the LORD."},{reference:"Acts 17:24-25",text:"God that made the world and all things therein, seeing that he is Lord of heaven and earth, dwelleth not in temples made with hands."}] },
    // Lord's Day 47
    { n:122, ld:"Lord's Day 47", lname:"Hallowed Be Thy Name",
      q:"What does the first petition mean?",
      a:"Hallowed be your name means, Help us to really know you, to bless, worship, and praise you for all your works and for all that shines forth from them: your almighty power, wisdom, kindness, justice, mercy, and truth. And it means, Help us to direct all our living — what we think, say, and do — so that your name will never be blasphemed because of us but always honored and praised.",
      p:[{reference:"Psalm 119:137",text:"Righteous art thou, O LORD, and upright are thy judgments."},{reference:"Matthew 5:16",text:"Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."}] },
    // Lord's Day 48
    { n:123, ld:"Lord's Day 48", lname:"Thy Kingdom Come",
      q:"What does the second petition mean?",
      a:"Your kingdom come means, Rule us by your Word and Spirit in such a way that more and more we submit to you. Keep your church strong, and add to it. Destroy the devil's work; destroy every force which revolts against you and every conspiracy against your Word. Do this until your kingdom is so complete and perfect that in it you are all in all.",
      p:[{reference:"Psalm 122:6",text:"Pray for the peace of Jerusalem: they shall prosper that love thee."},{reference:"Matthew 16:18",text:"Upon this rock I will build my church; and the gates of hell shall not prevail against it."}] },
    // Lord's Day 49
    { n:124, ld:"Lord's Day 49", lname:"Thy Will Be Done",
      q:"What does the third petition mean?",
      a:"Your will be done on earth as it is in heaven means, Help us and all people to reject our own wills and to obey your will without any back talk. Your will alone is good. Help us one and all to carry out the work we are called to, as willingly and faithfully as the angels in heaven.",
      p:[{reference:"Romans 12:2",text:"And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."},{reference:"Titus 2:11-12",text:"For the grace of God that bringeth salvation hath appeared to all men, Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly."}] },
    // Lord's Day 50
    { n:125, ld:"Lord's Day 50", lname:"Give Us Our Daily Bread",
      q:"What does the fourth petition mean?",
      a:"Give us today our daily bread means, Do take care of all our physical needs so that we come to know that you are the only source of everything good, and that neither our work and worry nor your gifts can do us any good without your blessing. And so help us to give up our trust in creatures and to put our trust in you alone.",
      p:[{reference:"Psalm 104:27-28",text:"These wait all upon thee; that thou mayest give them their meat in due season. That thou givest them they gather."},{reference:"Matthew 6:25-26",text:"Take no thought for your life, what ye shall eat, or what ye shall drink...Is not the life more than meat, and the body than raiment?"}] },
    // Lord's Day 51
    { n:126, ld:"Lord's Day 51", lname:"Forgive Us Our Debts",
      q:"What does the fifth petition mean?",
      a:"Forgive us our debts, as we also have forgiven our debtors means, Because of Christ's blood, do not hold against us, poor sinners that we are, any of the sins we do or the evil that constantly clings to us. Forgive us just as we are fully determined, as evidence of your grace in us, to forgive our neighbors.",
      p:[{reference:"Psalm 51:1",text:"Have mercy upon me, O God, according to thy lovingkindness: according unto the multitude of thy tender mercies blot out my transgressions."},{reference:"Matthew 6:14-15",text:"For if ye forgive men their trespasses, your heavenly Father will also forgive you."}] },
    // Lord's Day 52
    { n:127, ld:"Lord's Day 52", lname:"Lead Us Not Into Temptation",
      q:"What does the sixth petition mean?",
      a:"And lead us not into temptation, but deliver us from the evil one means, By ourselves we are too weak to hold our own even for a moment. And our sworn enemies — the devil, the world, and our own flesh — never stop attacking us. And so, Lord, uphold us and make us strong with the strength of your Holy Spirit, so that we may not go down to defeat in this spiritual struggle, but may firmly resist our enemies until we finally win the complete victory.",
      p:[{reference:"Matthew 26:41",text:"Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak."},{reference:"1 Peter 5:8",text:"Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour."}] },
    { n:128, ld:"Lord's Day 52", lname:"Lead Us Not Into Temptation",
      q:"What does your conclusion to this prayer mean?",
      a:"For the kingdom and the power and the glory are yours forever means, We have made all these petitions of you because, as our all-powerful king, you both want to and are able to give us all that is good; and because your holy name, and not we ourselves, should receive all the glory, forever.",
      p:[{reference:"Romans 10:11",text:"For the scripture saith, Whosoever believeth on him shall not be ashamed."},{reference:"2 Peter 2:9",text:"The Lord knoweth how to deliver the godly out of temptations."}] },
    { n:129, ld:"Lord's Day 52", lname:"Lead Us Not Into Temptation",
      q:"What does that little word 'Amen' express?",
      a:"Amen means, This is sure to be! It is even more sure that God listens to my prayer than that I really desire what I pray for.",
      p:[{reference:"Isaiah 65:24",text:"And it shall come to pass, that before they call, I will answer; and while they are yet speaking, I will hear."},{reference:"2 Corinthians 1:20",text:"For all the promises of God in him are yea, and in him Amen, unto the glory of God by us."}] },
  ];

  for (const q of qs) {
    await sql`
      INSERT INTO catechism_questions (catechism_id, number, section, section_name, question, answer, proof_texts)
      VALUES ('heidelberg', ${q.n}, ${q.ld}, ${q.lname}, ${q.q}, ${q.a}, ${JSON.stringify(q.p)})
      ON CONFLICT (catechism_id, number) DO UPDATE SET
        question=EXCLUDED.question, answer=EXCLUDED.answer,
        proof_texts=EXCLUDED.proof_texts, section=EXCLUDED.section,
        section_name=EXCLUDED.section_name
    `;
  }
  console.log('  ✓ Heidelberg: 129 questions');
}
